---
- name: Set logind key
  lineinfile:
    path: /etc/systemd/logind.conf
    line: "{{ item.key }}={{ item.value }}"
    regexp: >-
      ^#?{{ item.key }}=
  become: yes
  with_items:
  - key: HandlePowerKey
    value: "{{ laptop_power_key }}"
  - key: HandleSuspendKey
    value: "{{ laptop_suspend_key }}"
  - key: HandleHibernateKey
    value: "{{ laptop_hibernate_key }}"
  - key: HandleLidSwitch
    value: "{{ laptop_lid_switch }}"

- name: Check systemd-logind time
  timediff:
    src: /etc/systemd/logind.conf
    dest: systemd:systemd-logind
  register: logind_conf_vs_loaded

- name: Restart systemd-logind
  systemd:
    name: systemd-logind
    state: restarted
  when: logind_conf_vs_loaded.newer
  become: yes
